### ISSUE TITLE
Add vvv-hosts file when provisioning for Dashboard compatability

### ISSUE THREAD

**Issue by tedgeving** [JPry/vvv-base#31]
Hi, not sure if this is the right place to make this request, would it be possible to add a `vvv-hosts`  file with the site url to the provision directory when the site is provisioned?

It address a bug with the VVV-Dashboard not seeing provisioned sites.
https://github.com/topdown/VVV-Dashboard/issues/52

**Comment by JPry** [comment]
Hi @tedgeving,

> would it be possible to add a vvv-hosts file with the site url to the provision directory when the site is provisioned?

It would certainly be possible, but I don't think it is advisable. As mentioned on the [VVV Custom Domains and Hosts](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-domains-hosts/) page:

> The recommended way is to use the `vvv-custom.yml` file. `vvv-hosts` is supported for backwards compatibility...

Since the proper way going forward is to use the `vvv-custom.yml` file, I believe that VVV Dashboard should properly support this configuration.

With that said, if enough people want this feature I would be willing to add it. If this comment gets 10 thumbs-up reactions, I'll put this feature on the roadmap.

**Comment by tedgeving** [comment]
Hi,
Thanks for providing the repo, it saved me a ton of time when moving all of
my old development sites from VVV1 to VVV2.

I agree that VVV Dashboard should properly support the document
configuration.
