### ISSUE TITLE
Use htdocs option with download_wp

### ISSUE THREAD

**Issue by codepuncher** [JPry/vvv-base#34]
I'm currently in the process of migrating some local dev sites from WAMP over to vvv-base but I'm hitting an issue with cloning a project repo while also installing WP.

These repos follow a structure like this:

```
wp-content
-- themes
---- themename
.gitignore
composer.json
gulpfile.js
package.json
repo_actions.php
wp.base.dev.json
```

All I need is for this to be cloned before `download_wp` is triggered (don't need to use `wp` as I already have a WP databases setup for these projects).

Would there be any way we could change the order in which the options get loaded?
This would be very helpful for people in my situation with other developers simply adding the site to vvv-custom with the project repo (and the db options) and it'll be all ready for new people to jump into existing projects.

**Comment by JPry** [comment]
@codepuncher 

> All I need is for this to be cloned before download_wp is triggered (don't need to use wp as I already have a WP databases setup for these projects).

I understand what you're requesting, but I'm not sure I understand why the current order causes problems for your workflow. Is it simply that you don't want a DB to be created for your projects?

Is this essentially because you're using a custom DB connection (from #24) and don't want to bother with the setup/install portion?

I've actually been looking at breaking up the massive Provisioner class into separate pieces. This can be seen in [this history subset](https://github.com/JPry/vvv-base/compare/cd59a0ebf3ba7670870ea5a6ab2c182652191fb0...989288bca37dbb60346b56c32d0373e9d8eb6b77). There are still numerous pieces to break out, but with separate pieces it might be possible to have some kind of config to determine which pieces of provisioning you need.
